language: haskell

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh

install:
  - stack setup
  - stack install Agda

script:
  - ~/.local/bin/agda --verbose=1 --no-libraries --no-auto --safe VectorAppend.agda
